-- Post 테이블 생성
CREATE TABLE IF NOT EXISTS post (
    no          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    content     CLOB         NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    views       INT          NOT NULL DEFAULT 0
);

-- Post 태그 테이블 생성
CREATE TABLE IF NOT EXISTS post_tags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_no     BIGINT       NOT NULL,
    tag_name    VARCHAR(50)  NOT NULL,
    CONSTRAINT fk_post_tags_post FOREIGN KEY (post_no) REFERENCES post (no) ON DELETE CASCADE
);
