-- Post 테이블 생성
CREATE TABLE IF NOT EXISTS post (
    no          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    content     CLOB         NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    views       INT          NOT NULL DEFAULT 0
);
